WINDOW_TITLE = '评分工具'
WINDOW_POSITION_X = 300
WINDOW_POSITION_Y = 300
WINDOW_POSITION = (WINDOW_POSITION_X, WINDOW_POSITION_Y)
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
