from copy import deepcopy


WINDOW_TITLE = 'Mark Tool'
WINDOW_POSITION_X = 300
WINDOW_POSITION_Y = 300
WINDOW_POSITION = (WINDOW_POSITION_X, WINDOW_POSITION_Y)
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

TABLE_FILE_ROW_SPAN = 10
TABLE_FILE_COLUMN_SPAN = 20
TABLE_RULE_ROW_SPAN = 5
TABLE_RULE_COLUMN_SPAN = 8

TABLE_FILE_DEFAULT_HEADER = ['file name', 'score', 'total']
TABLE_FILE_HEADER = deepcopy(TABLE_FILE_DEFAULT_HEADER)
TABLE_RULE_HEADER = ['rule', 'weight']
RULES = {}

EDITABLE = True
